Update azure-pipeline.yaml to call mobilize plan
ni/nilrt-snac pull request #49
Opened 2024-12-12 16:47 UTC by texasaggie97

### Summary of Changes

This commit updates the azure-pipeline.yaml file
to call the mobilize plan that is defined in rtos_oetest.

### Justification

AB#2903031

### Testing

* [Pipeline run](https://dev.azure.com/ni/DevCentral/_build/results?buildId=11799246&view=logs&j=99c8e54b-67b9-5834-54a1-a3c2d9b921c3&t=99c8e54b-67b9-5834-54a1-a3c2d9b921c3)
* [Mobilize run](https://dashboard.ni.systems/dashboard/#/mobilize?plans=b0e2d532b89a11efb54e010101010000:b0e2d533b89a11efb3e6010101010000)

### Procedure

* [X] This PR: changes user-visible behavior, fixes a bug, or impacts the project's security profile; and so it includes a [CHANGELOG](https://github.com/ni/nilrt-snac/blob/master/docs/CHANGELOG.md) note.
* [X] I certify that the contents of this pull request complies with the [Developer Certificate of Origin](https://github.com/ni/nilrt-snac/blob/master/docs/CONTRIBUTING.md).

2024-12-12 18:28 UTC, texasaggie97 commented
/azp list

2024-12-12 18:34 UTC, texasaggie97 commented
/azp list

2024-12-12 23:14 UTC, AlexHearnNI requested changes

2024-12-12 23:14 UTC, AlexHearnNI commented on azure-pipeline.yaml
> +      displayName: Display Compiled Mobilize File
Did you ever get any use out of this step? If the previous step failed, then this step won't run, and if the previous step passed, then the compiled mobilize plan will be published in the report. I recommend removing this step.

2024-12-12 23:14 UTC, AlexHearnNI commented on azure-pipeline.yaml
> +      condition: succeeded()
This placeholder is no longer needed, right? Please remove it.

2025-01-02 20:56 UTC, texasaggie97 commented on azure-pipeline.yaml
>  - name: mobilize_ats_pr_build
Changed.

2025-01-02 20:59 UTC, texasaggie97 commented on azure-pipeline.yaml
>  trigger:
Changed `trigger:` to `pr:`. This should only trigger on PRs and not CIs.

2025-01-02 21:00 UTC, texasaggie97 commented on azure-pipeline.yaml
> +      displayName: Display Compiled Mobilize File
Removed.

2025-01-02 21:00 UTC, texasaggie97 commented on azure-pipeline.yaml
> +      condition: succeeded()
Removed.

2025-01-03 16:23 UTC, texasaggie97 commented on azure-pipeline.yaml
>    - python3
The mobilize plan uses the build machine as the "host" and therefore requires certain SW to be installed. This SW is installed on Windows but doesn't seem to be in Linux. The plan fails when ran on Linux. I believe we could make it work on Linux by adding another VM to act as the host but that would make the pipeline and mobilize plan more complicated since it would then need to configure both host and target.

Resolving this for now. If you feel strongly that two VMs is the direction we should go, then reopen this and I will start working on that.

2025-01-03 16:23 UTC, texasaggie97 commented on docs/CHANGELOG.md
> +* PR now runs sanity checks for `nilrt-snac`.
Removed

2025-01-03 18:23 UTC, AlexHearnNI commented on azure-pipeline.yaml
>    - python3
> The plan fails when ran on Linux.

I've never run a mobilize plan on Linux, but I'm surprised to hear that it fails. How exactly does the plan fail?

2025-01-03 18:40 UTC, AlexHearnNI commented on azure-pipeline.yaml
>    - python3
Oh, it looks like we use the nisyscfg library in the mobilize plan. So, nisyscfg must be installed on the Windows build machines but not the Linux build machines. Hmmm... Our solution for line endings is really brittle, but it doesn't look like there's an easy fix. We should revisit our line endings solution the first time it breaks.

2025-01-07 21:31 UTC, AlexHearnNI approved these changes

2025-01-07 21:31 UTC, merged